version: '3.8'

services:
  dia-tts:
    build: .
    image: dia-fastapi-server:latest
    container_name: dia-tts-server
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - DIA_GPU_MODE=auto
      - DIA_MAX_WORKERS=4
    volumes:
      - ./audio_outputs:/app/audio_outputs
      - ./audio_prompts:/app/audio_prompts
      - huggingface_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: dia-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dia-tts
    profiles:
      - with-proxy

volumes:
  huggingface_cache:
    driver: local